### ISSUE TITLE
TypeError : Bowser2.getParser is not a function

### ISSUE THREAD

**Issue by bas-d** [infobip/infobip-rtc-js-1.x-deprecated#2]
Loading the throws the following error:
```
Browser.ts:4 Uncaught TypeError: Bowser2.getParser is not a function
    at Browser.ts:4:37
    at node_modules/infobip-rtc/dist/util/Browser.js (Browser.ts:22:1)
    at __require (chunk-BQAOEP2F.js?v=5738714c:12:50)
    at node_modules/infobip-rtc/dist/gateway/InfobipGateway.js (InfobipGateway.ts:8:1)
    at __require (chunk-BQAOEP2F.js?v=5738714c:12:50)
    at node_modules/infobip-rtc/dist/InfobipRTC.js (InfobipRTC.ts:2:1)
    at __require (chunk-BQAOEP2F.js?v=5738714c:12:50)
    at node_modules/infobip-rtc/dist/index.js (index.ts:3:1)
    at __require (chunk-BQAOEP2F.js?v=5738714c:12:50)
    at dep:infobip-rtc:1:16
```
Steps to reproduce:
1. Scaffold project, for example with degit: `degit https://github.com/bas-d/vite-react-template`.
2. Add Infobip dependency: `npm install infobip-rtc --save`
3. Add the following code `src/App.tsx`: 
```
import { InfobipRTC } from 'infobip-rtc';
const infobipRTC = new InfobipRTC('fake');
```

When running vite (`npm run dev`) and checking `http://localhost:3000`, the page does not load because of the error.

**Comment by ajsa-terko** [comment]
Hi, 

I was able to reproduce it. A new version of the package infobip-rtc (1.10.44) with a fix for the described issue has been released. 

If the issue still persists, please let us know.

**Comment by bas-d** [comment]
I don't see the error anymore, thank you! But although this particular error is now resolved, it still does not load for me, throwing the following error:
```
MonitoredPeerConnection.ts:16 Uncaught TypeError: Class extends value [object Object] is not a constructor or null
    at MonitoredPeerConnection.ts:16:1
    at ApiEventEmitter.ts:5:38
    at node_modules/infobip-rtc/dist/util/ApiEventEmitter.js (ApiEventEmitter.ts:13:1)
    at __require (chunk-BQAOEP2F.js?v=01813194:12:50)
    at node_modules/infobip-rtc/dist/call/impl/DefaultCall.js (DefaultCall.ts:22:1)
    at __require (chunk-BQAOEP2F.js?v=01813194:12:50)
    at node_modules/infobip-rtc/dist/call/impl/DefaultOutgoingCall.js (DefaultOutgoingCall.ts:1:1)
    at __require (chunk-BQAOEP2F.js?v=01813194:12:50)
    at node_modules/infobip-rtc/dist/InfobipRTC.js (InfobipRTC.ts:6:1)
    at __require (chunk-BQAOEP2F.js?v=01813194:12:50)
```

**Comment by adnanel** [comment]
Hello

Please try again with 1.10.45, it should work now.

This seems to have been a compatibility issue with ViteJS.

**Comment by bas-d** [comment]
It works now, thanks a lot!
